### ISSUE TITLE
Change the styling of your application (demo)

### ISSUE THREAD

**Issue by vibs007** [dummyvibs007/Github-Tutorial#1]
I reviewed your styling and i would like to propose the change
```CSS
h1 {
  color: #e79914;
}
```
